#!/usr/bin/env bash
# Arch post-install: Hyprland + Noctalia (NVIDIA, discrete-only laptop)
# Run as your NORMAL user (not root) after first boot of a fresh archinstall (Minimal).
# Safe to re-run: every step checks before changing anything.
set -euo pipefail

say() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

if [ "$EUID" -eq 0 ]; then
  echo "Run this as your normal user (it uses sudo when needed)."
  exit 1
fi

pacman -Qq linux >/dev/null 2>&1 || {
  echo "This script assumes the standard 'linux' kernel (nvidia-open)."
  exit 1
}

sudo -v

say "Checking internet"
curl -fsI --max-time 8 https://archlinux.org >/dev/null 2>&1 || {
  echo "No internet. Connect first (nmcli device wifi connect <SSID> --ask)."
  exit 1
}

say "Installing packages"
sudo pacman -Syu --needed --noconfirm \
  nvidia-open nvidia-utils \
  hyprland polkit xdg-desktop-portal-hyprland xdg-desktop-portal-gtk xorg-xwayland \
  noctalia \
  pipewire pipewire-pulse wireplumber sof-firmware alsa-ucm-conf \
  networkmanager bluez bluez-utils power-profiles-daemon upower \
  kitty ttf-jetbrains-mono-nerd

say "Configuring NVIDIA (early KMS + modeset)"
sudo mkdir -p /etc/mkinitcpio.conf.d
echo 'MODULES+=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)' \
  | sudo tee /etc/mkinitcpio.conf.d/nvidia.conf >/dev/null
echo 'options nvidia_drm modeset=1' \
  | sudo tee /etc/modprobe.d/nvidia.conf >/dev/null
sudo mkinitcpio -P

say "Enabling services"
sudo systemctl enable --now NetworkManager bluetooth power-profiles-daemon upower

say "Auto-starting Hyprland on tty1"
LINE='[ -z "${WAYLAND_DISPLAY:-}" ] && [ "${XDG_VTNR:-}" = 1 ] && exec start-hyprland'
grep -qxF "$LINE" "$HOME/.bash_profile" 2>/dev/null || echo "$LINE" >> "$HOME/.bash_profile"

say "Mounting the NTFS 'Data' drive (if present)"
if DATA_DEV=$(sudo blkid -L Data 2>/dev/null) && ! grep -q '/mnt/data' /etc/fstab; then
  DATA_UUID=$(sudo blkid -s UUID -o value "$DATA_DEV")
  sudo mkdir -p /mnt/data
  echo "UUID=$DATA_UUID /mnt/data ntfs3 defaults,nofail,x-systemd.device-timeout=5s,uid=$(id -u),gid=$(id -g) 0 0" \
    | sudo tee -a /etc/fstab >/dev/null
  sudo systemctl daemon-reload
else
  echo "Skipped (no 'Data' partition found, or already in fstab)."
fi

say "Adding Noctalia to hyprland.lua"
CONF="$HOME/.config/hypr/hyprland.lua"
MARK='-- >>> noctalia setup >>>'
if [ -f "$CONF" ]; then
  if grep -qF -- "$MARK" "$CONF"; then
    echo "Already added."
  else
    cp "$CONF" "$CONF.bak"
    sed -i '/^hl\.config({ *autogenerated *= *true *})/d' "$CONF"
    cat >> "$CONF" <<'EOF'

-- >>> noctalia setup >>>
hl.on("hyprland.start", function()
  hl.exec_cmd("noctalia")
end)

hl.config({
  general = { gaps_in = 5, gaps_out = 10 },
  decoration = {
    rounding = 20,
    rounding_power = 2,
    shadow = { enabled = true, range = 4, render_power = 3, color = 0xee1a1a1a },
    blur = { enabled = true, size = 3, passes = 2, vibrancy = 0.1696 },
  },
})

-- glass blur on all Noctalia surfaces
hl.layer_rule({
  name = "noctalia",
  match = { namespace = "^noctalia-(bar-.+|notification|dock|panel|attached-panel|osd|window-switcher)$" },
  no_anim = true, ignore_alpha = 0.5, blur = true, blur_popups = true,
})

local nmod = "SUPER"
local nipc = "noctalia msg "
hl.bind(nmod .. " + Space", hl.dsp.exec_cmd(nipc .. "panel-toggle launcher"))
hl.bind(nmod .. " + A", hl.dsp.exec_cmd(nipc .. "panel-toggle control-center"))
hl.bind(nmod .. " + comma", hl.dsp.exec_cmd(nipc .. "settings-toggle"))
hl.bind("ALT + Tab", hl.dsp.exec_cmd(nipc .. "window-switcher"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(nipc .. "volume-up"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(nipc .. "volume-down"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd(nipc .. "volume-mute"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(nipc .. "brightness-up"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(nipc .. "brightness-down"))

hl.window_rule({
  match = { class = "dev.noctalia.Noctalia" },
  float = true,
  size = { 1080, 920 },
})
-- <<< noctalia setup <<<
EOF
    echo "Added (backup: $CONF.bak)."
  fi
  say "All done. Reboot, log in on tty1, and Hyprland + Noctalia will start."
else
  say "Almost done"
  cat <<'EOF'
hyprland.lua doesn't exist yet. Do this:
  1. Run: start-hyprland   (it creates a default config on first launch).
  2. Open a terminal (default bind is Super+Q).
  3. Run this script again to add the Noctalia config.
EOF
fi
