#!/usr/bin/env bash
# Lean glass-blur Hyprland setup for an NVIDIA discrete-only laptop (Arch Linux).
# Stack: Hyprland (Lua config, 0.55+) + Waybar + Fuzzel + Mako + Foot + Hyprlock/Hypridle + Hyprpaper.
#
# Safe by design:
#  - existing configs are backed up before anything is overwritten
#  - the Hyprland config starts from the default file shipped with YOUR installed
#    Hyprland version, then adds a small "glass" layer on top, so the base is
#    always valid for the version you have.
set -euo pipefail

CFG="$HOME/.config"
BK="$HOME/.config-backup-$(date +%Y%m%d-%H%M%S)"

echo "==> Installing packages (sudo needed)"
sudo pacman -S --needed --noconfirm \
  hyprland hyprlock hypridle hyprpaper hyprshot hyprpolkitagent \
  xdg-desktop-portal-hyprland qt5-wayland qt6-wayland \
  waybar fuzzel mako foot \
  brightnessctl cliphist wl-clipboard grim slurp \
  pipewire-pulse wireplumber power-profiles-daemon ttf-jetbrains-mono-nerd

echo "==> NVIDIA driver"
if pacman -Q nvidia-utils >/dev/null 2>&1; then
  echo "    NVIDIA driver already installed, skipping."
elif command -v chwd >/dev/null 2>&1; then
  echo "!!  CachyOS detected but no NVIDIA driver found."
  echo "    Install it with CachyOS's hardware tool (chwd) after this script, or re-run the installer with the NVIDIA option ticked."
else
  sudo pacman -S --needed --noconfirm nvidia-open nvidia-utils
fi

echo "==> Backing up existing configs to $BK"
mkdir -p "$BK"
for d in hypr waybar fuzzel mako foot; do
  if [ -e "$CFG/$d" ]; then cp -a "$CFG/$d" "$BK/$d"; fi
done
mkdir -p "$CFG"/{hypr,waybar,fuzzel,mako,foot} "$HOME/Pictures"

# ---------------------------------------------------------------- Hyprland (Lua)
# The glass layer: only documented Hyprland Lua functions are used.
cat > "$CFG/hypr/glass.lua" <<'EOF'

-- ===================== glass layer (hypr-glass-setup.sh) =====================
hl.config({
  general = {
    gaps_in = 5,
    gaps_out = 10,
    border_size = 1,
    col = {
      active_border = "rgba(ffffff66)",
      inactive_border = "rgba(ffffff1a)",
    },
  },
  decoration = {
    rounding = 14,
    -- Compositor-level transparency: makes EVERY app glassy (GTK, Qt, Electron)
    active_opacity = 0.92,
    inactive_opacity = 0.82,
    fullscreen_opacity = 1.0,
    blur = {
      enabled = true,
      size = 8,
      passes = 3,
      xray = false,            -- true glass: floating windows blur what is behind them
      ignore_opacity = true,
      new_optimizations = true,
      noise = 0.015,
      contrast = 0.9,
      brightness = 1.0,
      vibrancy = 0.17,
      vibrancy_darkness = 0.0,
      popups = true,
    },
    shadow = {
      enabled = true,
      range = 24,
      render_power = 3,
    },
  },
  misc = {
    vfr = true,                -- redraw only when something changes (saves power)
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
    force_default_wallpaper = 0,
  },
})

-- Blur for the bar, launcher and notifications
for _, ns in ipairs({ "waybar", "launcher", "notifications" }) do
  hl.layer_rule({ match = { namespace = ns }, blur = true, ignore_alpha = 0.2 })
end

-- Autostart (kept minimal for RAM)
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("waybar")
  hl.exec_cmd("mako")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("wl-paste --watch cliphist store")
end)

-- Extra keybinds (the default binds stay as they are)
hl.bind("SUPER + RETURN", hl.dsp.exec_cmd("foot"))
hl.bind("SUPER + D", hl.dsp.exec_cmd("fuzzel"))
hl.bind("SUPER + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind("SUPER + SHIFT + V", hl.dsp.exec_cmd("cliphist list | fuzzel --dmenu | cliphist decode | wl-copy"))
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))
-- ===================== end glass layer =====================
EOF

DEFAULT_LUA="/usr/share/hypr/hyprland.lua"
if [ -f "$DEFAULT_LUA" ]; then
  cp "$DEFAULT_LUA" "$CFG/hypr/hyprland.lua"
  # use foot as the default terminal, and drop the "autogenerated" warning line
  sed -i 's/local terminal *= *"[^"]*"/local terminal = "foot"/' "$CFG/hypr/hyprland.lua"
  sed -i '/hl.config({ *autogenerated *= *true *})/d' "$CFG/hypr/hyprland.lua"
  cat "$CFG/hypr/glass.lua" >> "$CFG/hypr/hyprland.lua"
  echo "==> Hyprland config installed (shipped default + glass layer)"
else
  echo
  echo "!! Could not find $DEFAULT_LUA (Hyprland older than 0.55, or a different layout)."
  echo "   The glass layer was saved to $CFG/hypr/glass.lua but not applied."
  echo "   Start Hyprland once so it generates its default config, then run:"
  echo "     cat $CFG/hypr/glass.lua >> $CFG/hypr/hyprland.lua"
  echo
fi

# Wallpaper (hyprpaper >= 0.8 config format). Put an image at ~/Pictures/wallpaper.jpg
cat > "$CFG/hypr/hyprpaper.conf" <<'EOF'
wallpaper {
    monitor =
    path = ~/Pictures/wallpaper.jpg
    fit_mode = cover
}
splash = false
EOF

cat > "$CFG/hypr/hypridle.conf" <<'EOF'
general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 180
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
EOF

cat > "$CFG/hypr/hyprlock.conf" <<'EOF'
background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    inner_color = rgba(20,22,30,0.5)
    outer_color = rgba(255,255,255,0.25)
    font_color = rgb(230,233,239)
    fade_on_empty = true
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 64
    color = rgb(230,233,239)
    position = 0, 100
    halign = center
    valign = center
}
EOF

# ---------------------------------------------------------------- Waybar
cat > "$CFG/waybar/config.jsonc" <<'EOF'
{
  "layer": "top",
  "position": "top",
  "height": 34,
  "margin-top": 6,
  "margin-left": 10,
  "margin-right": 10,
  "modules-left": ["hyprland/workspaces"],
  "modules-center": ["clock"],
  "modules-right": ["cpu", "memory", "pulseaudio", "network", "battery", "tray"],

  "hyprland/workspaces": { "format": "{id}", "on-click": "activate" },
  "clock": { "format": "{:%a %d %b  %H:%M}" },
  "cpu": { "format": " {usage}%", "interval": 3 },
  "memory": { "format": " {used:0.1f}G", "interval": 5 },
  "pulseaudio": { "format": "{icon} {volume}%", "format-muted": " muted", "format-icons": { "default": ["", "", ""] }, "on-click": "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle" },
  "network": { "format-wifi": " {signalStrength}%", "format-ethernet": "󰈀", "format-disconnected": "󰤭" },
  "battery": { "format": "{icon} {capacity}%", "format-icons": ["", "", "", "", ""], "states": { "warning": 25, "critical": 12 } },
  "tray": { "spacing": 8 }
}
EOF

cat > "$CFG/waybar/style.css" <<'EOF'
* {
  font-family: "JetBrainsMono Nerd Font";
  font-size: 13px;
  border: none;
  min-height: 0;
}

window#waybar {
  background: rgba(20, 22, 30, 0.45);
  color: #e6e9ef;
  border-radius: 14px;
  border: 1px solid rgba(255, 255, 255, 0.10);
}

#workspaces button {
  padding: 0 9px;
  margin: 4px 2px;
  color: #9aa0b4;
  background: transparent;
  border-radius: 10px;
}

#workspaces button.active {
  color: #ffffff;
  background: rgba(255, 255, 255, 0.16);
}

#clock, #cpu, #memory, #pulseaudio, #network, #battery, #tray {
  padding: 0 10px;
}

#battery.warning { color: #f9e2af; }
#battery.critical { color: #f38ba8; }
EOF

# ---------------------------------------------------------------- Fuzzel (launcher)
cat > "$CFG/fuzzel/fuzzel.ini" <<'EOF'
[main]
font=JetBrainsMono Nerd Font:size=12
prompt="❯ "
width=40
lines=10
horizontal-pad=22
vertical-pad=16
inner-pad=8

[colors]
background=14161ebb
text=e6e9efff
match=89b4faff
selection=ffffff26
selection-text=ffffffff
border=ffffff33

[border]
width=1
radius=14
EOF

# ---------------------------------------------------------------- Mako (notifications)
cat > "$CFG/mako/config" <<'EOF'
font=JetBrainsMono Nerd Font 11
background-color=#14161e99
text-color=#e6e9efff
border-color=#ffffff33
border-size=1
border-radius=14
padding=14
margin=12
anchor=top-right
default-timeout=5000
max-visible=4
EOF

# ---------------------------------------------------------------- Foot (terminal)
cat > "$CFG/foot/foot.ini" <<'EOF'
[main]
font=JetBrainsMono Nerd Font:size=11
pad=12x12

[colors]
alpha=0.6
background=14161e
foreground=e6e9ef
EOF

echo "==> Enabling services"
sudo systemctl enable --now power-profiles-daemon || true

echo "==> Auto-start Hyprland when you log in on tty1 (no display manager needed)"
SHELL_NAME="$(basename "${SHELL:-/bin/bash}")"
if [ "$SHELL_NAME" = "fish" ]; then
  FISHCFG="$CFG/fish/config.fish"
  mkdir -p "$CFG/fish"
  if ! grep -q "# hypr-glass-autostart" "$FISHCFG" 2>/dev/null; then
    cat >> "$FISHCFG" <<'EOF'

# hypr-glass-autostart
if status is-login
    if test -z "$WAYLAND_DISPLAY"; and test "$XDG_VTNR" = "1"
        # NVIDIA (discrete-only laptop)
        set -gx LIBVA_DRIVER_NAME nvidia
        set -gx __GLX_VENDOR_LIBRARY_NAME nvidia
        set -gx NVD_BACKEND direct
        set -gx QT_QPA_PLATFORM "wayland;xcb"
        if type -q start-hyprland
            exec start-hyprland
        else
            exec Hyprland
        end
    end
end
EOF
  fi
else
  if [ "$SHELL_NAME" = "zsh" ]; then PROFILE="$HOME/.zprofile"; else PROFILE="$HOME/.bash_profile"; fi
  if ! grep -q "# hypr-glass-autostart" "$PROFILE" 2>/dev/null; then
    cat >> "$PROFILE" <<'EOF'

# hypr-glass-autostart
if [ -z "${WAYLAND_DISPLAY:-}" ] && [ "${XDG_VTNR:-}" = "1" ]; then
  # NVIDIA (discrete-only laptop)
  export LIBVA_DRIVER_NAME=nvidia
  export __GLX_VENDOR_LIBRARY_NAME=nvidia
  export NVD_BACKEND=direct
  export QT_QPA_PLATFORM="wayland;xcb"
  if command -v start-hyprland >/dev/null 2>&1; then exec start-hyprland; else exec Hyprland; fi
fi
EOF
  fi
fi

# Optional: download a wallpaper. Usage: WALLPAPER_URL=https://example.com/img.jpg bash hypr-glass-setup.sh
if [ -n "${WALLPAPER_URL:-}" ]; then
  echo "==> Downloading wallpaper"
  curl -fL "$WALLPAPER_URL" -o "$HOME/Pictures/wallpaper.jpg" || echo "!! Wallpaper download failed; add one manually."
fi

echo
echo "Done. Backups: $BK"
echo "1) Optional: put a wallpaper at ~/Pictures/wallpaper.jpg (colorful ones look best under glass)."
echo "2) Reboot, log in on the text console, and Hyprland starts by itself."
echo "3) Keys: SUPER+RETURN terminal, SUPER+D launcher, SUPER+L lock (plus Hyprland's defaults)."
echo "4) If Hyprland ever fails, press Ctrl+Alt+F2 for a normal console."
echo "5) After the first reboot, check: cat /sys/module/nvidia_drm/parameters/modeset  (should print Y)"
